### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by GomidesTs** [Br-Pneus/Instagram#2]
Insertion of project images

**Comment by VishalNayek** [comment]
Could you please elaborate the problem you're facing?

**Comment by GomidesTs** [comment]
Images are not responsive

**Comment by VishalNayek** [comment]
Show me how you want your website to look and I can help : )

**Comment by VishalNayek** [comment]
Hey! I've managed to get a fix. Mind if I make a pull request?

**Comment by GomidesTs** [comment]
I don't care, thank you very much

**Comment by VishalNayek** [comment]
I hope that helps. Thank you and Good luck! 😀
